### ISSUE TITLE
Removing non-empty chapters

### ISSUE THREAD

**Issue by ValooFX** [steffendx/GoNorth#1]
Currently, removing a chapter with the 'x' button removes it from the canvas, but clicking save afterwards just spits out errors if it was not empty when removing. It should not be removable when being non-empty (maybe print an error at this point). Or if possible give a confirmation dialog with the option to force remove it  (i guess this needs more work with handling missing references/cleanup etc. but could be nice to have)

**Comment by steffendx** [comment]
I will implemented an earlier check in the next release.

**Comment by steffendx** [comment]
Implemented with 84bcf7c67a048cbd19cd5fea1e91f459e5ed0695
