### ISSUE TITLE
Document docker deployment, diligently

### ISSUE THREAD

**Issue by alekratz** [steffendx/GoNorth#10]
Couldn't resist the alliteration.

I figured I'd make an issue for this so it doesn't fall off of the radar (mine, or anyone else's). Although docker exists for this repo, Github's wiki system is not friendly to contributions. Once the documentation repository, website, or directory gets created, I plan on making those changes ASAP.

**Comment by steffendx** [comment]
I've setup a new repo wor the wiki system to allow pull requests [here](https://github.com/steffendx/GoNorthWiki). I will setup an automated build which will sync the two repos.

And nice alliteration ;)

**Comment by alekratz** [comment]
Great! I'll start working on that documentation soon.

**Comment by steffendx** [comment]
I've setup an automated process to sync the [Wiki Repo](https://github.com/steffendx/GoNorthWiki) to the wiki.
