### ISSUE TITLE
[Bug] Apostrophes not supported in choice nodes

### ISSUE THREAD

**Issue by Alorel** [steffendx/GoNorth#112]
Looks like they don't get escaped so whatever you type in gets cut off - see screencap. I'm using v1.9.1.0.

https://user-images.githubusercontent.com/4998038/209573738-b28e167d-1a2a-4d9b-9981-398affa0b2be.mp4

**Comment by steffendx** [comment]
Oh, thanks for the bug report! Really helpful with the video. That should be an easy fix. I'll look into it and release a fix as soon as possible.

**Comment by steffendx** [comment]
Fixed with 84c60451babe76ca1ae0371e5110cc20821e60fe.
