### ISSUE TITLE
Planning Skills/Spells

### ISSUE THREAD

**Issue by Sehlor** [steffendx/GoNorth#12]
Only thing missing is this, a skill/spell planner like Item planner :)

**Comment by steffendx** [comment]
Good idea. Somehow forgot the skills a bit. I will implement this.

**Comment by Sehlor** [comment]
When you are at it, consider adding User-Groups and Assigning Tasks To User Groups or Users individaully. Thanks for an awesome project management tool ^^

**Comment by steffendx** [comment]
Implemented with 84bcf7c67a048cbd19cd5fea1e91f459e5ed0695
