### ISSUE TITLE
Adding task error

### ISSUE THREAD

**Issue by Wiadomy** [steffendx/GoNorth#16]
Hello, I get **Error: An error occured.** when trying to assign task to someone.
Debug says something about:
> Processing error XML: main element not found
> Area: http://localhost:5000/api/TaskApi/CreateTaskGroup?boardId=
> Row: 1, Column 1:

**Comment by steffendx** [comment]
It seems like you did not create a task board before trying to create a new task. Can you please click on **Switch Task Board** -> **Manage Task boards** and then create a new Task board on the new page. You can find more details on how to create a task board in the [Wiki](https://github.com/steffendx/GoNorth/wiki/Task-Management). If you do not see the manage task boards button you will have to assign the **TaskBoardManager** role to yourself in the [Administration Area](https://github.com/steffendx/GoNorth/wiki/Administration).
After creating a new task board switch back to the task board and try to create a new task group.  

I agree that its a bug that you can select the add task group and I will change this and disable the button and display a message that you must first create a board. Thank you for reporting this.

**Comment by steffendx** [comment]
Fixed with 84bcf7c67a048cbd19cd5fea1e91f459e5ed0695
