### ISSUE TITLE
Minified JS file incorrect case

### ISSUE THREAD

**Issue by pchan3** [steffendx/GoNorth#17]
the file projectManagement.viewmodel.min.js should be named 
projectManagement.ViewModel.min.js

I built a new server today with the latest release, and this issue prevented me from created a project. I'm not sure if Windows and IIS ignores capitilization. But my combination of Firefox+Ubuntu Client & Server+Nginx as a proxy is particular about it.

I've fixed it myself, by renaming the file.

Now I can get stuck in :)

**Comment by steffendx** [comment]
Thanks for reporting this! I will fix it.

**Comment by steffendx** [comment]
It seems like the file was not updated on your side while rebuilding. The capitalization should be fine in the repo.
