### ISSUE TITLE
[NotAnIssue] Upgrading note

### ISSUE THREAD

**Issue by ValooFX** [steffendx/GoNorth#18]
Just wanted to leave that here in case anyone else stumbles upon this too: when upgrading from 1.0 to 1.1 i was missing the new Evne module. I figured out that i had to assign the new roles to my account in the admin panel (and it only appeared after logging out and in again, refresh didn't do it).

**Comment by steffendx** [comment]
I've also updated the release description to make sure people know they have to add the new roles.
