### ISSUE TITLE
[Feature Request] Random Name Generator

### ISSUE THREAD

**Issue by Wiadomy** [steffendx/GoNorth#19]
Hello, what would you think about adding a fantasy name generator to the character creator?
Often people don't know how they should name a character, a quick generator could help them.
There are opensource generator, for example https://github.com/felladrin/fantasy-name-generator

**Comment by steffendx** [comment]
A name generator is an interesting idea. But I think a way to configure this would be very helpful to tweek it in your style of names.  
I will integrate a simple version in the next release.

**Comment by steffendx** [comment]
Implemented with 5685305a4eef73b83ca01602e083ae18cfd6d786
