### ISSUE TITLE
Usability - node canvas initial view with nodes

### ISSUE THREAD

**Issue by ValooFX** [steffendx/GoNorth#2]
When placing nodes on the canvas while it is offset (Position not at 0,0), i.e. a large negative value, the next time the graph loads they are out of view and one could easily think it is empty (maybe a minimap could help?).

**Comment by steffendx** [comment]
A minimap is a great idea. I will implement a collapsable minimap below the position display.

**Comment by steffendx** [comment]
Implemented with 84bcf7c67a048cbd19cd5fea1e91f459e5ed0695
