### ISSUE TITLE
[Feature Request] Pictures/Icons for Categories

### ISSUE THREAD

**Issue by pchan3** [steffendx/GoNorth#20]
This is primarily for the Items section, but could be for other parts of GoNorth.

A description field for categories would also be useful, and this could be viewed as part of a 'tooltip'/hovering over the category before clicking.

**Comment by steffendx** [comment]
This is a good idea. I will add this in the next release.

**Comment by steffendx** [comment]
Implemented with 5685305a4eef73b83ca01602e083ae18cfd6d786

Regarding the size reduction: Please create a new issue for this to help me keep track of the different issues. Thank you.
