### ISSUE TITLE
[Feature Request] Exports

### ISSUE THREAD

**Issue by Merrenwen** [steffendx/GoNorth#28]
Export feature please :)  Even something simple to start out would be fantastic :)

**Comment by steffendx** [comment]
I am currently working on this and hopefully I will be finished with this soon. The export will allow JSON and exporting to a script based on templates which you can customize to fit to your needs.

**Comment by Merrenwen** [comment]
Wow that sounds fantastic!  I can't wait. Our project sorely needs this.  Thank you so much for creating it!
