### ISSUE TITLE
[Feature Request] Kirja (Wiki) Editor QoL Changes

### ISSUE THREAD

**Issue by jsnee** [steffendx/GoNorth#29]
I've been having some trouble with the editor used for the Wiki pages (Kirja). Most notably, I have difficulty removing formatting (heading styles) or a table of contents when set/inserted by accident. I have a few suggestions/thoughts:

- My initial thoughts led me to try to update the 'bootstrap-wysiwyg' library to latest version of the actively developed fork ([steveathon/bootstrap-wysiwyg](https://github.com/steveathon/bootstrap-wysiwyg)). However, I found a few issues that hindered my ability to simply update the library. I noticed you appear to be using a customized version of bootstrap-wysiwyg and you introduced a localization transformations to the library.
- My second thought is a suggestion for either introducing a toggle button to the editor that would allow direct modification of the underlying HTML (Similar to how you can using [Summernote](https://github.com/summernote/summernote/)).

**Comment by steffendx** [comment]
The ability to switch to HTML mode is a great idea. I will implement this in the next release.

**Comment by steffendx** [comment]
Implemented with a3f4c8ab47db717e7eb9c670aece5752c31a8f1f
