### ISSUE TITLE
Karta Map Marker Links Not Switching Map

### ISSUE THREAD

**Issue by jsnee** [steffendx/GoNorth#30]
When placing a Karta marker on a map in the Karta module, clicking on the marker title link doesn't cause the map to switch.

Note: I think the root problem was that with the change from hash to query notation, Map.KartaMarker.prototype.loadContent wasn't updated.

**Comment by steffendx** [comment]
Thank you for reporting this bug. I will fix this.

**Comment by steffendx** [comment]
Fixed with a3f4c8ab47db717e7eb9c670aece5752c31a8f1f
