### ISSUE TITLE
Bug / improvement: Lock times are too long

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#47]
Hello!

I want to start off by stating that this is a wonderful peace of software, and we're very pleased with some testing we have given it the past couple of days.

While our testing, we did notice that some page locks were very long. We we're testing it out with several users. Even though these users closed the page in question, and clicked around in other pages of GoNorth, all the pages visited before this remained locked for a pretty extensive time (we didn't explicitly count, but could've been 15 minutes easily). Especially when trying to work on a large map with several people, this becomes quite the issue.

Please let me know if this is intended or not. Perhaps some kind of lock time configuration setting could be added, or perhaps going to a different page will unlock the previous one.

Let me know, and thanks again for making this great software!

**Comment by steffendx** [comment]
Hi,

thanks for the feedback! I am really happy to hear that GoNorth can help you.  

Your idea to release the locks on navigation and make the lock time configurable makes a lot of sense and I will include this in the upcoming release. The next release should be done next week or the week after.

**Comment by steffendx** [comment]
Implemented with the latest [release](https://github.com/steffendx/GoNorth/releases/tag/v1.8.1.0). The lock will now be released on navigation or closing of the current page. Also you can now configure the lock refresh interval in the appsettings.json.
