### ISSUE TITLE
Improve linking towards other components from quest & dialogue boards

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#48]
Hello again!

I come with another improvement to propose; hopefully you don't mind. We like this tool and we hope to share some of our thoughts with you on how we can improve it.

During our time with GoNorth, we currently notice how something is missing which we think could add value. Basically, we'd like to propose workflow improvements to making quests & dialogue. I'll elaborate below.

When designing a quest, there's naturally multiple steps to go through. Most noticeably, during a single quest, there may be several dialogues. Currently the dialogue board and quest boards are fully separate, which can remain as it, but I think workflow wise there could be an improvement where we could link / reference between the two.

For example, let's say I'm designing the "My awesome quest" quest. During this awesome quest, we have five dialogue sequences. Workflow wise, it's is rather tedious to go back and forth between this quest and the dialogues, having to manually look for these entries. We propose to add something like a generic "link box" (similar to Player line, NPC line, Choice, Action and Condition boxes) in which one could create a direct reference to a quest, another dialogue, or even things like items. This box could be used in both quest boards and dialogue boards, because both have their use cases for referencing something.

I hope I'm not asking too much, but when linking between quest boards and dialogue boards (and visa versa), we're hoping it would also be possible to link to a specific box within these boards, and have the screen automatically center / focus on said box.

If you find it useful, below are some user stories I could think of if this helps;

- As a user, I want to have a link/reference box in the quest board, so that I can reference and navigate to referenced items, NPCs, other quests, dialogues, skills, .... and improve my workflow efficiency. 
- As a user, I want to have a link/reference box in the dialogue board, so that I can reference and navigate to referenced items, NPCs, quests, dialogues, skills, .... and improve my workflow efficiency.

Please share us your thoughts.

**Comment by steffendx** [comment]
Hey,

that sounds like a good idea. Linking to both the board in general or a specific node is a great idea. I think it would then make sense to indicate that a node is the target of a link by displaying a special icon.
If a node is deleted that is referenced by a quest or dialog I would display an additional warning on delete to highlight to the user that this certain node is referenced by a quest or dialog.

I will include something like this in the upcoming release.

**Comment by steffendx** [comment]
Implemented with the latest [release](https://github.com/steffendx/GoNorth/releases/tag/v1.8.1.0). A new reference node is now supported.
