### ISSUE TITLE
Feature request: Word count in dialogue and quest boards

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#50]
Hello!

Best wishes for 2021! I come again today with a proposal, which I hope can be added to the base product.

What I come to propose today is a small feature to add a word count on quest (text boxes) and dialogue boards. Allow me to explain the use case, as I can imagine that this doesn't seem very useful at first glance.

When building a game, one may hire contractors to do small parts of the game. For example, side quests. These contractors are commonly paid on a per-word basis. When someone, as a contractor, builds a side quest, then the payout of this is done based on the amount of words in that quest and/or dialogue. Currently, we didn't find an easy or straight forward way to simply count the words, hence why I'd like to propose this improvement. Alternatives, such as ArcWeave, do have this functionality (but are in return missing a lot of functionality that GoNorth does offer).

Please refer to the below user story if this adds further clearance;

As a project manager / team lead, I would like to be able to see a word count on quest and dialogue boards, so that I can easily calculate contractor payouts for quests/dialogue that this person worked on.

Please share us your thoughts.

**Comment by steffendx** [comment]
Hi,

thanks for the idea and best wishes to you too!  

Your idea sounds reasonable in the context you outlined. I will include statistics in general (amount of nodes, words and so on) in an upcoming release. Since I am currently finalizing the current release (christmas and new years eve took some time where I could not continue to work on it), this will not be included in that release.

**Comment by steffendx** [comment]
Implemented with the [release v1.8.5.0](https://github.com/steffendx/GoNorth/releases/tag/v1.8.5.0). Statistics are supported for dialogs, quests and wiki.
