### ISSUE TITLE
Empty Screen.

### ISSUE THREAD

**Issue by aknight2015** [steffendx/GoNorth#55]
I've followed the directions, went perfectly smooth. I go to localhost:5000 and all I have is a screen that has "Welcome to Project <Project name>". Nothing else.
![BlankScreen](https://user-images.githubusercontent.com/47067592/112203170-9f868980-8be8-11eb-8ea0-4737d2c45aea.png)

**Comment by steffendx** [comment]
Have you granted yourself all the Roles? It seems like you dont have any roles assigned.  

For this navigate to the Administration in the menu at the top. In the user list select the star next to your user and in the dialog grant yourself all the roles:
![image](https://user-images.githubusercontent.com/31102478/112211286-fe192b00-8c1b-11eb-99de-fac17404cfdf.png)

**Comment by aknight2015** [comment]
I've assigned roles, same problem.

**Comment by aknight2015** [comment]
Nevermind. Fixed. I logged out and logged back in. IT's fixed. Thanks.

**Comment by steffendx** [comment]
Ah yes, sorry I forgot to mention that you will have to sign out and back in again.
Happy to hear it works now!
