### ISSUE TITLE
Bug: Text doesn't properly scale with zooming in and out

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#57]
Good day,

When zooming in and out, in the quest and dialogue box view, the text does not scale together with the boxes. The text seems to always remain the same size. In larger quests and dialogues, where zooming out would be very useful, the feature becomes unusable because the text doesn't scale down with the boxes, resulting in text falling behind the borders of the box and not being readable anywhere.

Another small annoyance that we noticed together with this; when zooming in and out, the zooming doesn't happen on the cursor, but rather the top left of the screen. It makes zooming in and out on specific locations rather difficult, and requires the user to also active move towards the right position during the zooming action.

Currently we run v1.8.1.0. Have not updated yet to the latest version, but I don't see any mention of this issue in the history, so I assume this issue is still there.

Still loving the software; keep it up!

**Comment by steffendx** [comment]
Thanks for the feedback! 

Since I use the zoom feature not that much I did not bothered me much so far, but seeing that people seem to use the zoom feature more than I thought I will take care of this in the upcoming release.

**Comment by steffendx** [comment]
Fixed with [v1.9.0.0](https://github.com/steffendx/GoNorth/releases/tag/v1.9.0.0)
