### ISSUE TITLE
Feature request: annotate arrows / lines between nodes in quest and dialogue views

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#58]
Good day once again;

I come today with a small feature request I hope you can consider. It's a small, but handy option. When making larger quests & dialogue nodes, it is sometimes unclear what the flow is between nodes is when there are multiple possible flows. We'd like to propose a small addition to both the quest and dialogue view, to be able to annotate (add text on) lines & arrows between nodes. With this, we should be able to easily specify what each flow means by annotating the lines.

In the form of a user story;

As a content creator, I want to be able to annotate the lines between quest & dialogue nodes, so that I can better clarify what each possible flow does or is caused by

I also want to mention that we are very happy and thankful for your continued support towards all of our feature requests & bug reports. Can we buy you a coffee or beer somewhere?

**Comment by steffendx** [comment]
Hi,  

Good idea! Adding an annotation to a connection using a double click or something similiar should work and would be fairly easy to implement. 
I will add a functionality like that in the upcoming release.  

The gesture for buying me a coffee or beer is very much appreciated, but I am good thanks!

**Comment by steffendx** [comment]
Implemented with [v1.9.0.0](https://github.com/steffendx/GoNorth/releases/tag/v1.9.0.0). Upon hovering over a node connection you can now use the gear icon to provide an annotation.
