### ISSUE TITLE
Unable to run Deployment First run from Docker

### ISSUE THREAD

**Issue by oaguy1** [steffendx/GoNorth#6]
I ran the command ```docker-compose up``` to bring up the web app. After the docker machines are brought up, I was able to navigate to http://localhost:5000 and saw the login screen. I set a password in appsettings.json for "FirstTimeDeploymentPassword," I then went to http://localhost:5000/Deployment. I keep getting a 500 response with the app console reading:
```
web_1    | warn: GoNorth.Controllers.DeploymentController[0]
web_1    |       User tried to access first time deployment page while not valid.
```

Any idea on what can resolve this?

Attached is a screenshot with my current docker version running on macOS 10.13.3 (17D47).

![screen shot 2018-02-27 at 14 25 59](https://user-images.githubusercontent.com/2355614/36728680-469e6f04-1bca-11e8-85ac-821e2e563080.png)

**Comment by alekratz** [comment]
Did you set the "FirstTimeDeploymentPassword" before, or after the `docker-compose up`? If you did it after, you'll need to run `docker-compose up --build`.

If that doesn't fix it for you, what does your `appsettings.json` file look like?

**Comment by oaguy1** [comment]
Ah! That would probably do it. Probably just going to wait until #7 gets merged at this point, as I want the persistent deploy data and the key fix.

**Comment by oaguy1** [comment]
Still having an issue after pulling the latest master and running `docker-compose up --build`. I made sure my appsettings.json file had a **FirstTimeDeploymentPassword** password. Any further advice?

**Comment by steffendx** [comment]
Do you still just get the error message `User tried to access first time deployment page while not valid.`. If so, did you also adjust the **appsettings.docker.json** file and then run the `docker-compose up --build` command?
