### ISSUE TITLE
Feature: Autosave, save shortcut or local storage progress

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#66]
Hello again,

Today, I bring forth another feature request we'd like to propose after extensively using GoNorth. We've noticed that, currently, there is no auto save feature, nor any temporarily saving based on local storage for instance. When building content end to end (NPCs, monsters, skills, quests, dialogue), and having many tabs open as a result, one will likely accidentally close the page or navigate to a different page. Doing either of those causes all unsaved progress to get lost.

I'd like to propose a few options to improve the overall saving functionality & workflow. There are a few options, which I'll elaborate below;

* As a content creator, I want to have an auto save feature, so that I don't lose major progress when forgetting to use the button

A lot of modern web-based content editing software has an autosave, shortcut or local storage implementation. It has come to an unfortunate surprise to some of my team members that GoNorth currently does not have any of these, resulting in a bit of work getting lost.

* As a content creator, I want to have a save shortcut (such as CTRL+S) to save my document, so that I don't have to remove my hand from the keyboard towards my house

While nothing major, a small addition could include a shortcut to save. I can imagine that, while working on the larger pages, writing out wiki's, quest setups or dialogue flows, one doesn't want to manually use the mouse to press the save button. A short-cut to save could be a small improvement to workflow.

* As a content creator, I want to have unsaved progress be saved in the browser's local storage, so that even if I don't save, the progress is still kept after accidentally navigating to a different page or closing the page entirely

Perhaps the most important one; when auto saving is not an option (which currently there isn't yet), most users would expect their progress to be saved in the browsers local storage. This allows them to swap pages, close tabes, close the browser entirely, and they would still have their work-in-progress changes. This feature naturally does not replace the save functionality all together, but can greatly help a user in preventing loss of work.

As always, we are currently very pleased with GoNorth and we hope you'll consider these three features. Would love to hear back from you.

**Comment by steffendx** [comment]
Hi,  

thanks for the feedback! An Auto-Save Feature as well as a shortcut for saving sounds like a great ideas to prevent data loss and does not sound like a lot of work, so I can easily include something like that in the upcoming release.  

In contrast the local storage approach might be a bit more work to make sure that no version conflicts occure. Therefore I would refrain from implementing a function like that for the next release. But as you mentioned, an autosave should already prevent data loss and thefore not make this feature high priority for the moment.

**Comment by steffendx** [comment]
Implemented with [v1.9.0.0](https://github.com/steffendx/GoNorth/releases/tag/v1.9.0.0). Auto save will automatically save your progress. In addition a check is implemented that will ask for confirmation upon leaving a page with unsaved changes.  
Ctrl+s can be used to save your changes.
