### ISSUE TITLE
Publish executable releases for installers and/or portable versions of the app (e.g., via GitHub Actions)

### ISSUE THREAD

**Issue by Duckwhale** [steffendx/GoNorth#69]
As you've probably noticed, multiple people have remarked on the setup process being too complicated and error-prone. As a potential user, I'd also agree that there should be a very simple way of running the application locally that "just works ". The possibility of things not working aside, it should also be very fast to get started since otherwise some users won't bother giving the app a try.

Where I'm unsure is in how far there exist tools to create this for the technology you're using. Once that's been researched, you could set up a build pipeline to automatically attach the installer/portables to each release.

That part I've recently set up myself, using GitHub actions, which seems to be the simplest method of doing this. I could provide some assistance since I still remember most of the details :)

**Comment by steffendx** [comment]
You are right, a setup like that would be a great benefit. I will research on how to build a good setup for the project. Once this is done I will check how to integrate it.  

At the moment I am using Azure DevOps for the builds. But GitHub Actions sounds pretty interesting so I will get back to you once I am ready with my research and setup. Thanks for the offer!

**Comment by steffendx** [comment]
Implemented with [c80d0012afd10cf470c6705613b47e9650f6e9cd](https://github.com/steffendx/GoNorth/commit/c80d0012afd10cf470c6705613b47e9650f6e9cd)
