### ISSUE TITLE
[Feature Request] Export a quest

### ISSUE THREAD

**Issue by TheN96** [steffendx/GoNorth#70]
I think the real strength of GN as a lore/story building tool is that you can export the data in an easy way. I've already worked on being able to automatically generate characters purely off the NPC JSON, items and skills also. 

I think its worth having one for quests. Currently it cannot be exported

**Comment by steffendx** [comment]
A simple JSON export should be fairly easy for a quest. I will include something like that in the next release.

**Comment by TheN96** [comment]
Hi @steffendx , I'm not trying to rush anything, but could you let me know an estimate of an ETA for this export? I'm currently in the process of a full process of the exported data from GN right now, and having the quests/Aika would be great. If there is any way I can possibly help, let me know. I'm not good with JS at all but maybe a little bit of C#.

**Comment by steffendx** [comment]
Hi, I was moving the last couple of weeks which took a lot of my time. Now I am almost done and I think I can finish the next release in a couple of weeks.

Thanks for offering your help, but I should manage now that the move is done!

**Comment by steffendx** [comment]
Implemented with [c80d0012afd10cf470c6705613b47e9650f6e9cd](https://github.com/steffendx/GoNorth/commit/c80d0012afd10cf470c6705613b47e9650f6e9cd)
