### ISSUE TITLE
[Feature Request] Hiding children nodes 

### ISSUE THREAD

**Issue by TheN96** [steffendx/GoNorth#72]
Creation of very large number of nodes can become quickly overwhelming, even with the navigation window at the top left. Being able to hide all child nodes from any parent could be very helpful in organizing the node graph.

Especially since I'm writing dialogue for the player per chapter, grouping nodes and hiding them under a specific node (a reference to the chapter for example), would make it easier to focus on another branch.

**Comment by steffendx** [comment]
Thats a pretty interesting idea! 

So to summarize:
 * You would want to add tags to nodes (i.e. the chapter)
 * Then hide / show nodes based on these tags

Another approach would be:
 * Implement multi select (which would be helpful for dragging anyways)
 * Support for hiding the selection

What do you think would be the better approach for your requirement?

**Comment by TheN96** [comment]
I think the multi-select is an excellent idea. 

For hiding children though, I still think that being able to do it from a parent is useful, otherwise you'd have to select possibly a lot of nodes every time. 

I think both hiding selected nodes and hide from parent (like a button on parent nodes?) Is useful. 

Tagging is also excellent, I thought you had annotations in the latest release?

**Comment by steffendx** [comment]
Great. I think hiding from parent is also fairly easy and makes a lot of sense. 

Multiselect is also something I will try and include in the upcoming Release.

I will skip tagging for now since this will be a quite a bit work and it does not seem to offer that much off a benefit for now. Your starting node approach sounds perfectly fit for the job.

**Comment by TheN96** [comment]
> Great. I think hiding from parent is also fairly easy and makes a lot of sense. 
> 
> Multiselect is also something I will try and include in the upcoming Release.
> 
> I will skip tagging for now since this will be a quite a bit work and it does not seem to offer that much off a benefit for now. Your starting node approach sounds perfectly fit for the job.

Thanks for that! Can't wait for the new release.

**Comment by steffendx** [comment]
Implemented with [c80d0012afd10cf470c6705613b47e9650f6e9cd](https://github.com/steffendx/GoNorth/commit/c80d0012afd10cf470c6705613b47e9650f6e9cd)
