### ISSUE TITLE
[Feature Request] Map marker export with coordinates

### ISSUE THREAD

**Issue by TheN96** [steffendx/GoNorth#76]
I can see that the movement targets for the daily routine events has latitude and longitude like so:

`"MovementTarget": {
        "MapId": "84b13232-7897-44fb-a7de-2d35aa651430",
        "Lat": 55.379112,
        "Lng": -65.03201,
        "Name": "testEvent",
        "ExportName": "testEventMarker"
      },`

in the NPC export. 
As such, it would be good to attach these coordinate variables to marker exports. I think the easiest place to do this is just add it as fields to the marker exports along with the ID of the marker and map (such as adding to the actionData for actions):

`"ActionData": "{\"mapId\":\"84b13232-7897-44fb-a7de-2d35aa651430\",\"markerId\":\"7cee098b-b36a-4c80-880c-92f36d0ff0cc\",\"markerType\":\"Note\",\"movementState\":\"\"}",`

However, a better way might be to export the map in terms of marker exports with their types similar to the movement target above and we just use the Ids to link them. This would be extremely useful for things like auto-generating maps from this export and using coordinates to place items/npcs.  Something like:

`mapID: <string>,
markers: [
 {markerType: <string>,
  markerId: <string>,
  lat: <float>,
  lng: <float>,
  exportName: <string>
}, ....
]
}`

While the map and marker Id's can be exported, however, to my knowledge, there isn't a way to use it without manually creating  objects and copy-pasting Id's.

**Comment by steffendx** [comment]
I am not sure if I fully understand your requirement.  
Do you want to have these coordinates when exporting actions or would you want an export button in the map form?

**Comment by TheN96** [comment]
Hi steffendx, thank you for your quick reply. I think having it as a button on the map form is better since it will be less things on the action export and can be referenced via Id.

**Comment by steffendx** [comment]
Alright, that makes sense! Thanks for the input.

I will implement a button which will generate a JSON export similiar to the ones for Npcs and so on.

**Comment by steffendx** [comment]
Implemented with [c80d0012afd10cf470c6705613b47e9650f6e9cd](https://github.com/steffendx/GoNorth/commit/c80d0012afd10cf470c6705613b47e9650f6e9cd)
