### ISSUE TITLE
[Mod help] All fields can have additionalScriptNames

### ISSUE THREAD

**Issue by TheN96** [steffendx/GoNorth#77]
I think this is just a toggle somewhere but I cannot find it. 
![image](https://user-images.githubusercontent.com/59158064/135753410-db8392f6-2522-4382-ab45-0ca605b7e006.png)
Some fields can have additionScriptNames but not all. I'm thinking of using these as const's for importing fields without using their name.

**Comment by steffendx** [comment]
Since these fields can not be exported to a script it does not make sense for my setup to provide additional script names.

But I can implement a toggle that allows you to enable to specify additional script names for those fields in the appsettings file. I can include this in the next release.

**Comment by steffendx** [comment]
Implemented with [c80d0012afd10cf470c6705613b47e9650f6e9cd](https://github.com/steffendx/GoNorth/commit/c80d0012afd10cf470c6705613b47e9650f6e9cd)
