### ISSUE TITLE
Feature request: Being able to color notes on map views

### ISSUE THREAD

**Issue by MrDienns** [steffendx/GoNorth#78]
Hello again,

Today I come with a small feature request; being able to specify a color when creating a note on the map view. Currently they are all white. When having a large number of these notes, it may become difficult to navigate. Having the ability to color these notes would allow users to give each note its own category. This could make navigation on maps with lots of notes considerably easier.

Still rocking GoNorth internally!

Would love to hear back

**Comment by steffendx** [comment]
Implemented with [c80d0012afd10cf470c6705613b47e9650f6e9cd](https://github.com/steffendx/GoNorth/commit/c80d0012afd10cf470c6705613b47e9650f6e9cd)
