### ISSUE TITLE
[Feature Request] Allow labels/notes to be added to maps (Karta)

### ISSUE THREAD

**Issue by ValooFX** [steffendx/GoNorth#9]
Labels or notes could help identify certain places or quest locations. It would be nice to have this option in karta.
(And btw. there seems to be no way to exit the marker placement mode once an option from the left panel is selected)

**Comment by Wiadomy** [comment]
Aye, seems like a good idea for me!

**Comment by steffendx** [comment]
I will think about this, since these would be somewhat similiar to the Kirja (wiki) Notes. What would your usecase for this be compared to the wiki markers or the quest markers to mark quest locations?

**Comment by ValooFX** [comment]
I thought about this, when i wanted to tag the homes of my characters. Those don't need extra wiki page entries as they have no meaning, only as map decoration. Having to create empty pages for them would just clutter the list of more important entries.
Another use case i could see are vistas (like in Guild wars 2). They don't need explicite descriptions, a name is enough, but there can be many of them.

**Comment by steffendx** [comment]
For marking the home of an npc I would suggest using the npc markers. Beeing able to mark an area as dangerous for example sounds like a good idea. I've planned to implement a feature for marking polygons on the map in the features and this might be useful for marking areas as dangerous (or similiar).  
I will implement this feature with an upcoming release. But I will focus on exporting first, so this might take a few weeks.

**Comment by steffendx** [comment]
Implemented with 5685305a4eef73b83ca01602e083ae18cfd6d786

**Comment by ValooFX** [comment]
It's nice that they are implemented now, but would it be possible to have them not just display "A"/their icon in the map view but their title or an abbreviation thereof (that would make them way more useful)?

**Comment by steffendx** [comment]
You mean that the title should be in the Marker? Hmm that might be possible but still a bit more work. Could you create a new issue for this? This will help me tracking the issue a lot more. Thank you.
