### ISSUE TITLE
Feature Request: GoNorth Backup system

### ISSUE THREAD

**Issue by mcarpenter622** [steffendx/GoNorth#90]
It would be very convenient to be able to backup/restore the GoNorth system in case of system failure. Do you have any suggestions on how this could be done?

**Comment by steffendx** [comment]
I use the default MongoDB backup using `mongodump` and `mongorestore`. GoNorth stores all information apart from files in the MongoDB you configured. So once you made a backup using `mongodump` you can then restore that database using `mongorestore` and GoNorth should work again.  
You can find more information in regards to backing up a MongoDB at the official MongoDB site: [Back Up and Restore with MongoDB Tools](https://www.mongodb.com/docs/manual/tutorial/backup-and-restore-tools/)

To backup the files you can zip the following folders created by GoNorth inside the GoNorth folder and copy them to a backup server:
 * ItemImages
 * KirjaFiles
 * MapImages
 * NpcImages
 * SkillImages
 * TaskImages

To restore GoNorth you can then just unzip them back to their old location. Once the MongoDB is restored and the files are restored GoNorth will be up and running again.

Thanks for asking! This topic might be really helpful for others as well and I will include a wiki page for Backup / Restore for future reference.

**Comment by mcarpenter622** [comment]
Thank you!

**Comment by steffendx** [comment]
Always happy to help!

Closing the issue for now. If any more questions arise please reopen the ticket.
