### ISSUE TITLE
Dialog export: access npc object

### ISSUE THREAD

**Issue by mcarpenter622** [steffendx/GoNorth#93]
I was curious if it is possible to access the npc object during the export of the various tale nodes? My use case is this: I am trying to export the npc to golang. I would like to modify the function names in the dialog export to be unique per npc (ie include the npc Id in each function name) but i cannot figure out how to do so without a reference to the npc object or some global variable which I haven't been able to get to work.

**Comment by steffendx** [comment]
At the moment this is not possible I think. But it makes sense to be able to modify function names.
So to make the export more flexible I will allow you to modify the name of the generated function names and reference values like the object id in there.

**Comment by mcarpenter622** [comment]
So while I still think this could be useful, i was able to work around my golang export issue another way. Thank you for being so responsive.

Mark

**Comment by steffendx** [comment]
Thats great to hear! I will close the ticket for now then.
