### ISSUE TITLE
Feature Request - Tasks - Match task width to category width

### ISSUE THREAD

**Issue by mcarpenter622** [steffendx/GoNorth#98]
It surprised me a bit to see the tasks side by side with each other. Most other Task systems do not flow that way. (See Trello, JIRA, etc)

![image](https://user-images.githubusercontent.com/13891542/168170631-8e951060-4794-4fd9-8be0-d953db082929.png)

**Comment by steffendx** [comment]
I used Azure DevOps as a reference in which the tasks flow like this. I personally like it like this since it uses the space pretty well.
Do you think this is not easily readable?

**Comment by mcarpenter622** [comment]
Ah. I've never used that tool before so the flow felt strange. If it was
intentional this isn't needed. Thanks!

**Comment by steffendx** [comment]
Alright. Thanks for reporting this anyways!
